=== google-code-export/tv-and-movies-meta-data-fetcher/tv-and-movies-meta-data-fetcher/etc/MediaInfoFetcher-XmlStore.dtd
<!--
	This is the DTD that describes MediaInfoFetcher 
	(http://code.google.com/p/tv-and-movies-meta-data-fetcher/) 
	XMLStore file format. 
-->
<!ELEMENT store (show|film)*>

<!ELEMENT show (description?,genre*,season*)>

<!ATTLIST show
  id       NMTOKENS  #REQUIRED     
  imageUrl CDATA     #IMPLIED
  name     CDATA     #IMPLIED
  sourceId CDATA     #REQUIRED
  url      CDATA     #IMPLIED
>

<!ELEMENT description (short?,long?)>

<!ELEMENT short (#PCDATA)>

<!ELEMENT long (#PCDATA)>

<!ELEMENT season (episode|special)*>

<!ATTLIST season
  detailedListingUrl  CDATA   #IMPLIED
  listingUrl          CDATA   #IMPLIED
  number              CDATA   #REQUIRED
>

<!ELEMENT episode (summary?,(director*|writer*|guestStar*|file*)*)>

<!ATTLIST episode
  episodeId          CDATA  #REQUIRED
  firstAired         CDATA  #IMPLIED
  number             CDATA  #REQUIRED
  rating             CDATA  #IMPLIED
  firstAired         CDATA  #IMPLIED
  title              CDATA  #IMPLIED
  url                CDATA  #IMPLIED
  showEpisodeNumber  CDATA  #IMPLIED
>

<!ELEMENT special (summary?,(director*|writer*|guestStar*|file*)*)>

<!ATTLIST special
  episodeId          CDATA  #REQUIRED
  firstAired         CDATA  #IMPLIED
  number             CDATA  #REQUIRED
  rating             CDATA  #IMPLIED
  firstAired         CDATA  #IMPLIED
  title              CDATA  #IMPLIED
  url                CDATA  #IMPLIED
  showEpisodeNumber  CDATA  #IMPLIED
>

<!ELEMENT summary (#PCDATA)>
<!ELEMENT film (description?,country?,(genre*|certification*|guestStar*|director*|writer*|chapter*|file*)*)>

<!ATTLIST film
	id            NMTOKENS  #REQUIRED
	imageUrl      CDATA     #IMPLIED 
	rating        CDATA     #IMPLIED
	releaseDate   CDATA     #IMPLIED
	sourceId      CDATA     #IMPLIED
	title         CDATA     #IMPLIED
	url           CDATA     #IMPLIED
>

<!ELEMENT country EMPTY>

<!ATTLIST country
  name      CDATA              #REQUIRED
  url      CDATA    #IMPLIED
>

<!ELEMENT genre EMPTY>

<!ATTLIST genre
  name      CDATA              #REQUIRED
  preferred (true|false) "false"
>

<!ELEMENT director EMPTY>

<!ATTLIST director
  url      CDATA    #IMPLIED
  name     CDATA    #REQUIRED
>

<!ELEMENT writer EMPTY>

<!ATTLIST writer
  url      CDATA    #IMPLIED
  name     CDATA    #REQUIRED
>

<!ELEMENT guestStar EMPTY>

<!ATTLIST guestStar
  url      CDATA    #IMPLIED
  name     CDATA    #REQUIRED
>

<!ELEMENT file EMPTY>

<!ATTLIST file
    location CDATA #REQUIRED
>

<!ELEMENT chapter EMPTY>

<!ATTLIST chapter
    name    CDATA    #REQUIRED
	number  NMTOKENS #REQUIRED
>

<!ELEMENT certification EMPTY>

<!ATTLIST certification
  certification CDATA #REQUIRED
  country CDATA       #REQUIRED
>

=== google-code-export/tv-and-movies-meta-data-fetcher/tv-and-movies-meta-data-fetcher/tests/org/stanwood/media/store/xmlstore/expectedXmlStoreResults.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE store SYSTEM "http://tv-and-movies-meta-data-fetcher.googlecode.com/svn/trunk/tv-and-movies-meta-data-fetcher/etc/MediaInfoFetcher-XmlStore.dtd">
<store>
  <show id="58448" imageUrl="http://image.com.com/tv/images/b.gif"
    name="Eureka" sourceId="tvcom" url="http://www.tv.com/show/58448/summary.html">
    <description>
      <short><![CDATA[Small town. Big secret. A car accident leads U.S. Marshal Jack Carter into the top-secret Pacific Northwest town of Eureka. For decades, the United States government has relocated the world's geniuses to Eureka, a town where innovation and chaos have lived hand in hand. Eureka is produced by NBC...]]></short>
      <long><![CDATA[Small town. Big secret.

A car accident leads U.S. Marshal Jack Carter into the top-secret Pacific Northwest town of Eureka. For decades, the United States government has relocated the world's geniuses to Eureka, a town where innovation and chaos have lived hand in hand.

Eureka is produced by NBC Universal Cable Studio and filmed in Vancouver, British Columbia, Canada.
]]></long>
    </description>
    <genre name="SCIFI"/>
    <genre name="Drama"/>
    <season
      detailedListingUrl="http://www.tv.com/show/58448/episode_guide.html?printable=1"
      listingUrl="http://www.tv.com/show/58448/episode_listings.html?season=1" number="1">
      <episode episodeId="784857" firstAired="2006-10-10" number="1"
        rating="1.0" showEpisodeNumber="1" title="Pilot" url="http://www.tv.com/eureka/pilot/episode/784857/summary.html">
        <summary>A car accident leads U.S. Marshal Jack Carter into the unique Pacific Northwest town of Eureka.</summary>
        <director name="Harry" url="http://test/"/>
        <writer name="Write a lot" url="http://test/a"/>
        <guestStar name="sally" url="http://test/sally"/>
        <guestStar name="Cedric" url="http://test/cedric"/>
        <file location="$rootMedia$/Eureka/1x01 - blah"/>
      </episode>
      <episode episodeId="800578" firstAired="2006-10-11" number="2"
        rating="9.5" showEpisodeNumber="2" title="Many Happy Returns" url="http://www.tv.com/eureka/many-happy-returns/episode/800578/summary.html">
        <summary>Carter and the other citizens of Eureka attend the funeral of Susan and Walter Perkins. Much to their surprise, Susan makes a return to Eureka as a woman who is very much alive!</summary>
        <file location="$rootMedia$/Eureka/1x02 - blah"/>
      </episode>
    </season>
    <season
      detailedListingUrl="http://www.tv.com/show/58448/episode_guide.html?printable=2"
      listingUrl="http://www.tv.com/show/58448/episode_listings.html?season=2" number="2">
      <episode episodeId="800578" firstAired="2007-07-10" number="2"
        rating="0.4" showEpisodeNumber="13" title="Phoenix Rising" url="http://www.tv.com/eureka/phoenix-rising/episode/1038982/summary.html">
        <summary>Reaccustoming to the timeline restored in "Once in a Lifetime", Sheriff Carter investigates a series of sudden deaths.</summary>
        <file location="$rootMedia$/Eureka/2x13 - blah"/>
      </episode>
      <special episodeId="800578" firstAired="2007-07-09" number="0"
        rating="0.4" showEpisodeNumber="-1"
        title="Countdown to the Premiere" url="http://www.tv.com/heroes/heroes-countdown-to-the-premiere/episode/1228258/summary.html">
        <summary>Before the third season premiere, a brief recap of Seasons 1 and 2 and interviews with the cast at the premiere party is shown.</summary>
        <director name="JP" url="http://test/"/>
        <writer name="Write a lot" url="http://test/a"/>
        <writer name="Write a little" url="http://test/b"/>
        <guestStar name="bob" url="http://test/bob"/>
        <guestStar name="Write a little" url="http://test/fred"/>
        <file location="$rootMedia$/Eureka/000 - blah"/>
      </special>
    </season>
  </show>
  <show id="17552"
    imageUrl="http://image.com.com/tv/images/content_headers/program_new/17552.jpg"
    name="Heroes" sourceId="tvcom" url="http://www.tv.com/heroes/show/17552/summary.html">
    <description>
      <short><![CDATA[Heroes is a serial saga about people all over the world discovering that they have superpowers and trying to deal with how this change affects their lives. Some of the superheroes who will be introduced to the viewing audience include Peter Petrelli, an almost 30-something male nurse who suspect...]]></short>
      <long><![CDATA[Heroes is a serial saga about people all over the world discovering that they have superpowers and trying to deal with how this change affects their lives. Some of the superheroes who will be introduced to the viewing audience include Peter Petrelli, an almost 30-something male nurse who suspects he might be able to fly, Isaac Mendez, a 28-year-old junkie who has the ability to paint images of the future when he is high, Niki Sanders, a 33-year-old Las Vegas showgirl who begins seeing strange things in mirrors, Hiro Nakamura, a 24-year-old Japanese comic-book geek who literally makes time stand still, D.L. Hawkins, a 31-year-old inmate who can walk through walls, Matt Parkman, a beat cop who can hear other people's thoughts, and Claire Bennet, a 17-year-old cheerleader who defies death at every turn. As the viewing audience is discovering the nature of each hero's powers, the heroes themselves are discovering what having superpowers means to them as well as the larger picture of where their superpowers come from. Tune in each week to see how these heroes are drawn together by their common interest of evading the series' antagonist who wants to harvest their super-DNA for himself. Their ultimate destiny is nothing less than saving the world! The series will star Greg Grunberg (Alias), Leonard Roberts (Buffy the Vampire Slayer), Milo Ventimiglia (Gilmore Girls), and Hayden Panettiere (Ally McBeal, Guiding Light). Tim Kring (Crossing Jordan, Chicago Hope) is the series' creator. The pilot is set to be directed by Dave Semel (American Dreams, Buffy, the Vampire Slayer, Beverly Hills, 90210). Heroes will be produced by NBC/Universal/Tailwind. Summary revised with help from: space-cowboy]]></long>
    </description>
    <genre name="SCIFI"/>
    <genre name="Drama"/>
    <season
      detailedListingUrl="http://www.tv.com/show/17552/episode_guide.html?printable=1"
      listingUrl="http://www.tv.com/show/17552/episode_listings.html?season=1" number="1">
      <episode episodeId="1181337" firstAired="2006-11-11" number="1"
        rating="2.0" showEpisodeNumber="1" title="Heroe, Pilot" url="http://www.tv.com/eureka/pilot/episode/784857/summary.html">
        <summary>After a look into the future, Nathan's shooter is revealed. Matt chases him and winds up in a desert. Hiro receives an important message from his father. Sylar visits Claire. Maya gives Mohinder an idea for his research. Nathan recovers and gets a visit from Linderman.</summary>
        <director name="Whoever" url="http://Whoever/"/>
        <writer name="Write a lot" url="http://test/a"/>
        <guestStar name="sally" url="http://test/sally"/>
        <guestStar name="Cedric" url="http://test/cedric"/>
        <file location="$rootMedia$/Heroes/1x01 - hero"/>
      </episode>
    </season>
  </show>
  <film id="114814" imageUrl="http://test/image.jpg" rating="8.7"
    releaseDate="1995-08-25" sourceId="imdb" title="The Usual Suspects" url="http://www.imdb.com/title/tt0114814/">
    <description>
      <short><![CDATA[A boat has been destroyed, criminals are dead, and the key to this mystery lies with the only survivor and his twisted, convoluted story beginning with five career crooks in a seemingly random police lineup.]]></short>
      <long><![CDATA[Test description of the film]]></long>
    </description>
    <country name="USA" url="http://www.imdb.com/Sections/Countries/USA/"/>
    <genre name="Crime"/>
    <genre name="Drama" preferred="true"/>
    <genre name="Mystery"/>
    <genre name="Thriller"/>
    <certification certification="16" country="Iceland"/>
    <certification certification="R-18" country="Philippines"/>
    <certification certification="16" country="Argentina"/>
    <certification certification="MA" country="Australia"/>
    <certification certification="16" country="Brazil"/>
    <certification certification="14A" country="Canada"/>
    <certification certification="18" country="Chile"/>
    <certification certification="16" country="Denmark"/>
    <certification certification="K-16" country="Finland"/>
    <certification certification="U" country="France"/>
    <certification certification="16" country="Germany"/>
    <certification certification="IIB" country="Hong Kong"/>
    <certification certification="16" country="Hungary"/>
    <certification certification="18" country="Ireland"/>
    <certification certification="T" country="Italy"/>
    <certification certification="PG-12" country="Japan"/>
    <certification certification="16" country="Netherlands"/>
    <certification certification="R18" country="New Zealand"/>
    <certification certification="15" country="Norway"/>
    <certification certification="M/16" country="Portugal"/>
    <certification certification="M18" country="Singapore"/>
    <certification certification="PG (cut)" country="Singapore"/>
    <certification certification="18" country="South Korea"/>
    <certification certification="18" country="Spain"/>
    <certification certification="15" country="Sweden"/>
    <certification certification="18" country="UK"/>
    <certification certification="R" country="USA"/>
    <chapter name="The start" number="1"/>
    <chapter name="Second Chapter" number="2"/>
    <chapter name="The end" number="3"/>
    <director name="Bryan Singer" url="http://www.imdb.com/name/nm0001741/"/>
    <writer name="Christopher McQuarrie" url="http://www.imdb.com/name/nm0003160/"/>
    <guestStar name="Stephen Baldwin" url="http://www.imdb.com/name/nm0000286/"/>
